version: '3.8'
services:
  tests:
    image: buildkite/plugin-tester
    volumes:
    - .:/plugin
  lint:
    image: buildkite/plugin-linter
    command: ['--id', 'create1st/docker-security-check-plugin']
    volumes:
      - .:/plugin:ro